// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdNKLae2yHDl48zZfBCIVtFHHz4vLzj4w',
    appId: '1:1087118611111:web:c79495c830d3f831ecc182',
    messagingSenderId: '1087118611111',
    projectId: 'dwaara-c45f5',
    authDomain: 'dwaara-c45f5.firebaseapp.com',
    storageBucket: 'dwaara-c45f5.appspot.com',
    measurementId: 'G-ZVPGYVDLQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjpx63MsRNJJJd7cPodg6kTUF11mm_Kqw',
    appId: '1:1087118611111:android:d6ebefd8a56ab644ecc182',
    messagingSenderId: '1087118611111',
    projectId: 'dwaara-c45f5',
    storageBucket: 'dwaara-c45f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3WF5302X0-H1PJpSQY4tvf5zJZep0ywU',
    appId: '1:1087118611111:ios:5af607429adfd04aecc182',
    messagingSenderId: '1087118611111',
    projectId: 'dwaara-c45f5',
    storageBucket: 'dwaara-c45f5.appspot.com',
    iosClientId: '1087118611111-oda6moinhsp76um6k81aqdf1up1i119u.apps.googleusercontent.com',
    iosBundleId: 'com.example.dwaara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3WF5302X0-H1PJpSQY4tvf5zJZep0ywU',
    appId: '1:1087118611111:ios:5af607429adfd04aecc182',
    messagingSenderId: '1087118611111',
    projectId: 'dwaara-c45f5',
    storageBucket: 'dwaara-c45f5.appspot.com',
    iosClientId: '1087118611111-oda6moinhsp76um6k81aqdf1up1i119u.apps.googleusercontent.com',
    iosBundleId: 'com.example.dwaara',
  );
}
